CC = gcc
CFLAGS = -g

DEPS = Device.h CPU.h Memory.h
OBJ = Main.o CPU.o Device.o Memory.o

%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)
      
hellomake1: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS)

clean:
	rm -f *.o