CC = gcc
CFLAGS = -g
SDIR=Source
BDIR=Bin

DEPS = $(SDIR)/Device.h $(SDIR)/CPU.h $(SDIR)/Memory.h
OBJ = $(SDIR)/Main.o $(SDIR)/CPU.o $(SDIR)/Device.o $(SDIR)/Memory.o

%.o: %.c $(DEPS)
	$(CC) $(CFLAGS) -c -o $@ $<
      
$(BDIR)/hellomake1: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS)